name: Deploy API Docs to GitHub Pages

on:
  push:
    branches:
      - master  # or master if your repo uses that

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build ReDoc HTML
        run: |
          mkdir -p public
          npx redoc-cli bundle openapi.yaml -o public/redoc.html

      - name: Copy Swagger UI
        run: |
          mkdir -p public/swagger
          cp -r swagger/* public/swagger/
          cp swagger/index.html public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

