name: Deploy ReDoc to GitHub Pages

on:
  push:
    branches:
      - master  # or master (whichever is your default branch)

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build ReDoc HTML
        run: |
          mkdir public
          npx redoc-cli bundle openapi.yaml -o index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public


